name: Generate GitHub Contribution Snake

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
      - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout repository
        uses: actions/checkout@v2

      # Create the output directory
      - name: Create output directory
        run: mkdir -p dist

      # Generate the snake game SVG files
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Ensure the generated files exist
      - name: Ensure the generated files exist
        run: |
          ls dist
          test -f dist/github-snake.svg
          test -f dist/github-snake-dark.svg

      # Push the generated SVG files to the output branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}